#!/usr/bin/env python3
"""
EcoNexo System - Setup and Initialization Script
Run this before first use to configure the environment
"""

import os
import sys
from pathlib import Path


def print_header():
    """Print welcome header"""
    print("=" * 60)
    print("🎯 EcoNexo's System v2.0 - Setup")
    print("=" * 60)
    print()


def check_python_version():
    """Verify Python version"""
    print("📋 Checking Python version...")
    version = sys.version_info
    
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print("❌ ERROR: Python 3.8+ required")
        print(f"   Current version: {version.major}.{version.minor}.{version.micro}")
        return False
    
    print(f"✅ Python {version.major}.{version.minor}.{version.micro} detected")
    return True


def install_dependencies():
    """Install required packages"""
    print("\n📦 Installing dependencies...")
    
    try:
        import subprocess
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "--break-system-packages", "-r", "requirements.txt"],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("✅ Dependencies installed successfully")
            return True
        else:
            print("❌ Failed to install dependencies")
            print(result.stderr)
            return False
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def create_env_file():
    """Create .env file if it doesn't exist"""
    print("\n🔐 Setting up environment variables...")
    
    env_path = Path(".env")
    
    if env_path.exists():
        print("✅ .env file already exists")
        return True
    
    print("📝 Creating .env file...")
    
    # Get API keys from user
    print("\nTo use AI chat features, you need an API key.")
    print("You can skip this and add it later to the .env file.\n")
    
    anthropic_key = input("Enter your Anthropic API key (or press Enter to skip): ").strip()
    groq_key = input("Enter your Groq API key (optional, press Enter to skip): ").strip()
    
    # Create .env content
    env_content = f"""# EcoNexo System Configuration
# Generated by setup.py

# AI Provider API Keys
ANTHROPIC_API_KEY={anthropic_key or 'your_key_here'}
GROQ_API={groq_key or 'your_key_here'}

# Database Configuration
ECONEXO_DB_PATH=./data/econexo.db

# Application Settings
# Add custom settings here
"""
    
    try:
        env_path.write_text(env_content)
        print("✅ .env file created successfully")
        
        if not anthropic_key:
            print("\n⚠️  WARNING: No Anthropic API key provided.")
            print("   AI chat will not work until you add your key to .env")
        
        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False


def create_data_directory():
    """Create data directory for database"""
    print("\n📁 Creating data directory...")
    
    data_dir = Path("data")
    
    try:
        data_dir.mkdir(exist_ok=True)
        print("✅ Data directory ready")
        return True
    except Exception as e:
        print(f"❌ Failed to create data directory: {e}")
        return False


def initialize_database():
    """Initialize database schema"""
    print("\n🗄️  Initializing database...")
    
    try:
        import database as db
        db.init_database()
        print("✅ Database schema created")
        return True
    except Exception as e:
        print(f"❌ Database initialization failed: {e}")
        return False


def run_tests():
    """Optionally run test suite"""
    print("\n🧪 Would you like to run tests to verify installation?")
    response = input("Run tests? (y/n): ").strip().lower()
    
    if response == 'y':
        print("\n" + "=" * 60)
        print("Running test suite...")
        print("=" * 60 + "\n")
        
        try:
            import test_suite
            success = test_suite.run_tests()
            
            if success:
                print("\n✅ All tests passed!")
            else:
                print("\n⚠️  Some tests failed. Please check the output above.")
            
            return success
        except Exception as e:
            print(f"❌ Test execution failed: {e}")
            return False
    else:
        print("⏭️  Skipping tests")
        return True


def print_next_steps():
    """Print instructions for next steps"""
    print("\n" + "=" * 60)
    print("✨ Setup Complete!")
    print("=" * 60)
    print("\n📚 Next Steps:")
    print("\n1. Review your .env file and add API keys if you haven't")
    print("   - Get Anthropic key: https://console.anthropic.com/")
    print("   - Get Groq key: https://console.groq.com/")
    print("\n2. Start the application:")
    print("   streamlit run main.py")
    print("\n3. Open your browser at:")
    print("   http://localhost:8501")
    print("\n4. Create an account and start your productivity journey!")
    print("\n📖 For more information, see README.md")
    print("=" * 60)


def main():
    """Main setup function"""
    print_header()
    
    steps = [
        ("Python version", check_python_version),
        ("Dependencies", install_dependencies),
        ("Environment file", create_env_file),
        ("Data directory", create_data_directory),
        ("Database", initialize_database),
    ]
    
    for step_name, step_func in steps:
        if not step_func():
            print(f"\n❌ Setup failed at: {step_name}")
            print("Please fix the errors and run setup.py again.")
            sys.exit(1)
    
    # Optional test execution
    run_tests()
    
    print_next_steps()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)
